line-length = 79
exclude = [
  "notebooks",
]

[lint]
select = ["ALL"]
ignore = [
  # Documentation (pydocstyle)
  "D100",  # undocumented-public-module
  "D101",  # undocumented-public-class
  "D102",  # undocumented-public-method
  "D103",  # undocumented-public-function
  "D104",  # undocumented-public-package
  "D105",  # undocumented-magic-method
  "D106",  # undocumented-public-nested-class
  "D107",  # undocumented-public-init
  "D203",  # incorrect-blank-line-before-class
  "D212",  # multi-line-summary-first-line
  "D400",  # missing-trailing-period. D415 already covers this.
  "D413",  # missing-blank-line-after-last-section
  # Type annotations
  "ANN204",  # missing-return-type-special-method. I don't want to annotate __init__
  # Pycodestyle errors
  "E501",  # line-too-long. `ruff format` already fixes this.
  # Boolean trap
  "FBT001",  # boolean-type-hint-positional-argument
  "FBT003",  # boolean-positional-value-in-call
  # Logging
  "G004",  # logging-f-string
  # Import conventions
  "INP001",  # implicit-namespace-package
  # Naming conventions
  "N806",  # non-lowercase-variable-in-function
  "N812",  # lowercase-imported-as-non-lowercase
  # Pylint refactor
  "PLR0913",  # too-many-arguments
  "PLR2004",  # magic-value-comparison
  # Return values
  "RET504",  # unnecessary-assign
  # Bandit security
  "S101",  # assert. Useful in unit tests
  "S311",  # suspicious-non-cryptographic-random-usage
  # Print statements
  "T201",  # print,
  "T203",  # pprint
  # todo comments
  "TD002",  # missing-todo-author
  "TD003",  # missing-todo-link
  "TD005",  # missing-todo-description
  # Flake8-commas
  "COM812",  # missing-trailing-comma
  # eradicate
  "ERA001",  # commented-out-code
  # flake8-fixme
  "FIX002",  # line-contains-todo
  "FIX004",  # line-contains-hack
  # Ruff-specific
  "RUF005",  # collection-literal-concatenation. torch.Size cannot be unpacked
  # (PGH)
  "PGH004",  # blanket-noqa. Very convenient to use on LLM generated files.
  # (F)
  "F722",  # forward-annotation-syntax-error. Allows us to use jaxtyping to annotate shapes.
]
extend-safe-fixes = [
  "D200",  # unnecessary-multiline-doscring
  "PTH123",  # builtin-open. Seems to not work :(
  "EM102",  # f-string-in-exception
  "D415",  # missing-terminal-punctuation
]

[format]
docstring-code-format = true
